name: coverity-scan

# Controls when the action will run.
on:
  # Run this action on a schedule (we're allowed a maximum of two per day)
  schedule:
    - cron: '0 18 * * SUN' # Sunday at 18:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'qgis/o2'
    steps:
      - uses: actions/checkout@v2

      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt-get install --allow-unauthenticated g++ make cmake qtbase5-dev qt5keychain-dev qtscript5-dev qtwebengine5-dev
      - name: Configure O2
        run: |
          cmake . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=OFF \
            -Do2_BUILD_EXAMPLES:BOOL=ON \
            -Do2_SHOW_TRACE:BOOL=ON \
            -Do2_WITH_DROPBOX:BOOL=ON \
            -Do2_WITH_FACEBOOK:BOOL=ON \
            -Do2_WITH_FLICKR:BOOL=ON \
            -Do2_WITH_GOOGLE:BOOL=ON \
            -Do2_WITH_HUBIC:BOOL=ON \
            -Do2_WITH_KEYCHAIN:BOOL=ON \
            -Do2_WITH_MSGRAPH:BOOL=ON \
            -Do2_WITH_OAUTH1:BOOL=ON \
            -Do2_WITH_QT6:BOOL=OFF \
            -Do2_WITH_SKYDRIVE:BOOL=ON \
            -Do2_WITH_SMUGMUG:BOOL=ON \
            -Do2_WITH_SPOTIFY:BOOL=ON \
            -Do2_WITH_SURVEYMONKEY:BOOL=ON \
            -Do2_WITH_UBER:BOOL=ON \
            -Do2_WITH_VIMEO:BOOL=ON \
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=qgis%2Fo2" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      - name: Build with cov-build
        run: |
          pwd
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make -j$(nproc)
      - name: Submit to Coverity Scan
        run: |
          tar czvf o2.tgz cov-int
          curl \
            --form project=qgis%2Fo2 \
            --form token=$TOKEN \
            --form email=nyall.dawson@gmail.com \
            --form file=@o2.tgz \
            --form version=master \
            --form description="`git rev-parse --abbrev-ref HEAD` `git rev-parse --short HEAD`" \
            https://scan.coverity.com/builds?project=qgis%2Fo2
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
